### ISSUE TITLE
go-fuzz-build: non-standard import "..." in standard package "..."

### ISSUE THREAD

**Issue by saschagrunert** [dvyukov/go-fuzz#234] opened 2019-04-05 08:20 UTC
Hey :wave:, it seems that go-fuzz-build does not copy all necessary dependencies into the goroot. Usually I would expect that everything within `GOROOT/src` is also available in `/tmp/go-fuzz-build*/goroot/src`, right?

So if I run `go-fuzz-build` on my local machine, it errors with:
```
/tmp/go-fuzz-build695745724/goroot/src/go-fuzz-dep/main.go:10:2: non-standard import "runtime" in standard package "go-fuzz-dep"
```

If I modify the `github.com/dvyukov/go-fuzz/go-fuzz-build/main.go` like this, it works:
```go
func (c *Context) populateWorkdir() {
	// TODO: instead of reconstructing the world,
	// can we use a bunch of replace directives in a go.mod?

	// TODO: make all this I/O concurrent (up to a limit).
	// It's a non-trivial part of build time.
	// Question: Do it here or in copyDir?

	// TODO: See if we can avoid making toolchain copies,
	// using some combination of env vars and toolexec.
	// c.copyDir(filepath.Join(c.GOROOT, "src", "errors"), filepath.Join(c.workdir, "goroot", "src", "errors"))
	c.copyDir(filepath.Join(c.GOROOT, "src", "internal"), filepath.Join(c.workdir, "goroot", "src", "internal"))
	c.copyDir(filepath.Join(c.GOROOT, "src", "runtime"), filepath.Join(c.workdir, "goroot", "src", "runtime"))
	c.copyDir(filepath.Join(c.GOROOT, "src", "sync"), filepath.Join(c.workdir, "goroot", "src", "sync"))
	c.copyDir(filepath.Join(c.GOROOT, "src", "syscall"), filepath.Join(c.workdir, "goroot", "src", "syscall"))
	c.copyDir(filepath.Join(c.GOROOT, "src", "time"), filepath.Join(c.workdir, "goroot", "src", "time"))
	c.copyDir(filepath.Join(c.GOROOT, "src", "unsafe"), filepath.Join(c.workdir, "goroot", "src", "unsafe"))

	...
}
```

How do we want to handle this? I'm wondering why others do not have this issue... :thinking:

**Comment by dvyukov** [comment] 2019-04-05 08:22
Do you have a repro?
+ @josharian

**Comment by saschagrunert** [comment] 2019-04-05 08:27
I just followed the instructions on the README.md, installed the binaries and created a non-dependency package like this:

```go
package fuzz

func Fuzz(data []byte) int {
	return 0
}
```
then running `go-fuzz-build` within that directory results in:
```
/tmp/go-fuzz-build695745724/goroot/src/go-fuzz-dep/main.go:10:2: non-standard import "runtime" in standard package "go-fuzz-dep"
```

**Comment by dvyukov** [comment] 2019-04-05 08:44
Go version? go-fuzz version? fuzz package location? go-fuzz-build invocation?

**Comment by dvyukov** [comment] 2019-04-05 08:45
@josharian I see we now import a golang.org/x/tools package, which is not canned so users get a random version. Should we vendor it? Or modules already a thing?

**Comment by saschagrunert** [comment] 2019-04-05 08:55
> Go version? go-fuzz version? fuzz package location? go-fuzz-build invocation?

- go version go1.12.1 linux/amd64
- go-fuzz 9cfa592
- fuzz package: $GOPATH/src/github.com/saschagrunert/test
- go-fuzz-build invocation: `go-fuzz-build`

**Comment by dvyukov** [comment] 2019-04-05 09:00
I can't reproduce. I have go-fuzz on 9cfa592d57929860bc951b39c3ca41a2a9d4c919, go version go1.12 linux/amd64, created $GOPATH/src/github.com/saschagrunert/test and fuzz.go file there with the provided contents, cd there and run go-fuzz-build. It succeeds for me.
Also tried to run `go get -u github.com/dvyukov/go-fuzz/...` to update all deps. Still works.
There must be something else different in your env.

**Comment by saschagrunert** [comment] 2019-04-05 13:40
> I can't reproduce. I have go-fuzz on [9cfa592](https://github.com/dvyukov/go-fuzz/commit/9cfa592d57929860bc951b39c3ca41a2a9d4c919), go version go1.12 linux/amd64, created $GOPATH/src/github.com/saschagrunert/test and fuzz.go file there with the provided contents, cd there and run go-fuzz-build. It succeeds for me.
> Also tried to run `go get -u github.com/dvyukov/go-fuzz/...` to update all deps. Still works.
> There must be something else different in your env.

Okay, so is my working directory complete?

```
> go-fuzz-build -work
workdir: /tmp/go-fuzz-build287046846
failed to execute go build: exit status 1
/tmp/go-fuzz-build287046846/goroot/src/go-fuzz-dep/main.go:10:2: non-standard import "runtime" in standard package "go-fuzz-dep"

> tree /tmp/go-fuzz-build287046846
/tmp/go-fuzz-build287046846
├── gopath
│   └── src
│       ├── errors
│       │   └── errors.go
│       ├── github.com
│       │   ├── dvyukov
│       │   │   └── go-fuzz
│       │   │       ├── go-fuzz-defs
│       │   │       │   └── defs.go
│       │   │       └── go-fuzz-dep
│       │   │           ├── cover.go
│       │   │           ├── doc.go
│       │   │           ├── main.go
│       │   │           ├── sonar.go
│       │   │           └── sys_posix.go
│       │   └── saschagrunert
│       │       └── test
│       │           ├── fuzz.go
│       │           └── go.fuzz.main
│       │               └── main.go
│       ├── internal
│       │   ├── bytealg
│       │   │   ├── bytealg.go
│       │   │   ├── compare_amd64.s
│       │   │   ├── compare_native.go
│       │   │   ├── count_amd64.s
│       │   │   ├── count_native.go
│       │   │   ├── equal_amd64.s
│       │   │   ├── equal_native.go
│       │   │   ├── index_amd64.go
│       │   │   ├── index_amd64.s
│       │   │   ├── indexbyte_amd64.s
│       │   │   ├── indexbyte_native.go
│       │   │   └── index_native.go
│       │   ├── cpu
│       │   │   ├── cpu_amd64.go
│       │   │   ├── cpu.go
│       │   │   ├── cpu_x86.go
│       │   │   └── cpu_x86.s
│       │   └── race
│       │       ├── doc.go
│       │       └── norace.go
│       ├── runtime
│       │   ├── alg.go
│       │   ├── asm_amd64.s
│       │   ├── asm_ppc64x.h
│       │   ├── asm.s
│       │   ├── atomic_pointer.go
│       │   ├── cgocallback.go
│       │   ├── cgocall.go
│       │   ├── cgocheck.go
│       │   ├── cgo.go
│       │   ├── cgo_mmap.go
│       │   ├── cgo_sigaction.go
│       │   ├── chan.go
│       │   ├── compiler.go
│       │   ├── complex.go
│       │   ├── cpuflags_amd64.go
│       │   ├── cpuflags.go
│       │   ├── cpuprof.go
│       │   ├── cputicks.go
│       │   ├── debugcall.go
│       │   ├── debug.go
│       │   ├── defs_linux_amd64.go
│       │   ├── duff_amd64.s
│       │   ├── env_posix.go
│       │   ├── error.go
│       │   ├── extern.go
│       │   ├── fastlog2.go
│       │   ├── fastlog2table.go
│       │   ├── float.go
│       │   ├── funcdata.h
│       │   ├── go_tls.h
│       │   ├── hash64.go
│       │   ├── heapdump.go
│       │   ├── iface.go
│       │   ├── internal
│       │   │   ├── atomic
│       │   │   │   ├── asm_amd64.s
│       │   │   │   ├── atomic_amd64x.go
│       │   │   │   └── stubs.go
│       │   │   ├── math
│       │   │   │   └── math.go
│       │   │   └── sys
│       │   │       ├── arch_amd64.go
│       │   │       ├── arch.go
│       │   │       ├── intrinsics.go
│       │   │       ├── stubs.go
│       │   │       ├── sys.go
│       │   │       ├── zgoarch_amd64.go
│       │   │       ├── zgoos_linux.go
│       │   │       └── zversion.go
│       │   ├── lfstack_64bit.go
│       │   ├── lfstack.go
│       │   ├── lock_futex.go
│       │   ├── malloc.go
│       │   ├── map_fast32.go
│       │   ├── map_fast64.go
│       │   ├── map_faststr.go
│       │   ├── map.go
│       │   ├── mbarrier.go
│       │   ├── mbitmap.go
│       │   ├── mcache.go
│       │   ├── mcentral.go
│       │   ├── memclr_amd64.s
│       │   ├── mem_linux.go
│       │   ├── memmove_amd64.s
│       │   ├── mfinal.go
│       │   ├── mfixalloc.go
│       │   ├── mgc.go
│       │   ├── mgclarge.go
│       │   ├── mgcmark.go
│       │   ├── mgcstack.go
│       │   ├── mgcsweepbuf.go
│       │   ├── mgcsweep.go
│       │   ├── mgcwork.go
│       │   ├── mheap.go
│       │   ├── mprof.go
│       │   ├── msan0.go
│       │   ├── msize.go
│       │   ├── mstats.go
│       │   ├── mwbbuf.go
│       │   ├── netpoll_epoll.go
│       │   ├── netpoll.go
│       │   ├── os_linux_generic.go
│       │   ├── os_linux.go
│       │   ├── os_linux_noauxv.go
│       │   ├── os_nonopenbsd.go
│       │   ├── panic.go
│       │   ├── plugin.go
│       │   ├── print.go
│       │   ├── proc.go
│       │   ├── profbuf.go
│       │   ├── proflabel.go
│       │   ├── race0.go
│       │   ├── rdebug.go
│       │   ├── relax_stub.go
│       │   ├── rt0_linux_amd64.s
│       │   ├── runtime1.go
│       │   ├── runtime2.go
│       │   ├── runtime.go
│       │   ├── rwmutex.go
│       │   ├── select.go
│       │   ├── sema.go
│       │   ├── signal_amd64x.go
│       │   ├── signal_linux_amd64.go
│       │   ├── signal_sighandler.go
│       │   ├── signal_unix.go
│       │   ├── sigqueue.go
│       │   ├── sigtab_linux_generic.go
│       │   ├── sizeclasses.go
│       │   ├── slice.go
│       │   ├── softfloat64.go
│       │   ├── stack.go
│       │   ├── string.go
│       │   ├── stubs2.go
│       │   ├── stubs3.go
│       │   ├── stubs.go
│       │   ├── stubs_linux.go
│       │   ├── stubs_x86.go
│       │   ├── symtab.go
│       │   ├── sys_linux_amd64.s
│       │   ├── sys_nonppc64x.go
│       │   ├── sys_x86.go
│       │   ├── textflag.h
│       │   ├── time.go
│       │   ├── timestub2.go
│       │   ├── timestub.go
│       │   ├── traceback.go
│       │   ├── trace.go
│       │   ├── type.go
│       │   ├── typekind.go
│       │   ├── unaligned1.go
│       │   ├── utf8.go
│       │   ├── vdso_elf64.go
│       │   ├── vdso_linux_amd64.go
│       │   ├── vdso_linux.go
│       │   └── write_err.go
│       ├── sync
│       │   ├── atomic
│       │   │   ├── asm.s
│       │   │   ├── doc.go
│       │   │   └── value.go
│       │   ├── cond.go
│       │   ├── map.go
│       │   ├── mutex.go
│       │   ├── once.go
│       │   ├── pool.go
│       │   ├── runtime.go
│       │   ├── rwmutex.go
│       │   └── waitgroup.go
│       ├── syscall
│       │   ├── asm_linux_amd64.s
│       │   ├── dirent.go
│       │   ├── endian_little.go
│       │   ├── env_unix.go
│       │   ├── exec_linux.go
│       │   ├── exec_unix.go
│       │   ├── flock.go
│       │   ├── lsf_linux.go
│       │   ├── msan0.go
│       │   ├── net.go
│       │   ├── netlink_linux.go
│       │   ├── setuidgid_linux.go
│       │   ├── sockcmsg_linux.go
│       │   ├── sockcmsg_unix.go
│       │   ├── str.go
│       │   ├── syscall.go
│       │   ├── syscall_linux_amd64.go
│       │   ├── syscall_linux.go
│       │   ├── syscall_unix.go
│       │   ├── timestruct.go
│       │   ├── zerrors_linux_amd64.go
│       │   ├── zsyscall_linux_amd64.go
│       │   ├── zsysnum_linux_amd64.go
│       │   └── ztypes_linux_amd64.go
│       ├── time
│       │   ├── format.go
│       │   ├── sleep.go
│       │   ├── sys_unix.go
│       │   ├── tick.go
│       │   ├── time.go
│       │   ├── zoneinfo.go
│       │   ├── zoneinfo_read.go
│       │   └── zoneinfo_unix.go
│       └── unsafe
│           └── unsafe.go
└── goroot
    ├── pkg
    │   ├── include
    │   │   ├── asm_ppc64x.h
    │   │   ├── funcdata.h
    │   │   └── textflag.h
    │   └── tool
    │       └── linux_amd64
    │           ├── addr2line
    │           ├── api
    │           ├── asm
    │           ├── buildid
    │           ├── cgo
    │           ├── compile
    │           ├── cover
    │           ├── dist
    │           ├── doc
    │           ├── fix
    │           ├── link
    │           ├── nm
    │           ├── objdump
    │           ├── pack
    │           ├── pprof
    │           ├── test2json
    │           ├── trace
    │           └── vet
    └── src
        └── go-fuzz-dep
            ├── cover.go
            ├── defs.go
            ├── doc.go
            ├── main.go
            ├── sonar.go
            └── sys_posix.go

32 directories, 229 files

```

Is it intended that the `goroot` does not contain something like `runtime`?

**Comment by josharian** [comment] 2019-04-05 17:09
> Okay, so is my working directory complete?

No one is denying that things are not working correctly for you.

Please help us diagnose the issue, since we cannot reproduce it ourselves. Just to confirm, what commit is your package `golang.org/x/tools` at?

> I see we now import a golang.org/x/tools package, which is not canned so users get a random version. Should we vendor it? Or modules already a thing?

Probably we should switch to modules. I am not sure yet how many cycles I will have for go-fuzz over the coming week, but I can take this as a TODO.

**Comment by saschagrunert** [comment] 2019-04-06 08:42
> Please help us diagnose the issue, since we cannot reproduce it ourselves. Just to confirm, what commit is your package `golang.org/x/tools` at?

I'm currently using revision 052fc3cf of it. Thanks for taking your time to look into this issue. :)

**Comment by josharian** [comment] 2019-04-07 00:06
Thanks for the diagnosis. Before I saw your edits, I was about to ask for the output of `go list std`. :)

> except we do not rely on "go list" for obtaining the standard packages.

Asking `go list` is the officially preferred means. So we either need to fix `go list` or fix your distribution.

I'll start an issue in the core Go repo to discuss, and cc you there. I'm going to close this one in the meantime, since the issue appears not to be a go-fuzz-build issue.

**Comment by josharian** [comment] 2019-04-07 00:13
Filed https://github.com/golang/go/issues/31313; we can continue there.

**Closed by josharian** 2019-04-07 00:13 UTC
